### ISSUE TITLE
Énonce des TP SVP

### ISSUE THREAD

**Issue by benza86** [saibimajdi/TPAndroid#1]

**Comment by saibimajdi** [comment]
Hi benza86,

Thank you for reminding me about it!

- [TP #1](https://drive.google.com/open?id=0B3wiZKoya2iCaEhNVkI3S3R0UTQ)
- [TP #2](https://drive.google.com/open?id=0B3wiZKoya2iCZjdzSWJRUEtJRDQ)
- [TP #3](https://drive.google.com/open?id=0B3wiZKoya2iCQnNHUkx0YUlwYjQ)
- [TP #4](https://drive.google.com/open?id=0B3wiZKoya2iCY2R0bUFMSmtpb28)
- [TP #5](https://drive.google.com/open?id=0B3wiZKoya2iCUUQ0bTBzNXRvSHM)

Have a nice coding :)

**Comment by benza86** [comment]
Thank You Bro,
Nice Jobs
Best
